<a href="https://colab.research.google.com/github/Karanuderani07/ML_LEARNING/blob/main/_Exp_1_Basic_of_Pandas_%26_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.9.0
aiofiles                              24.1.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.11.15
aiosignal                             1.4.0
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.8
ale-py                                0.11.2
altair                                5.5.0
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.9.0
argon2-cffi                           25.1.0
argon2-cffi-bindings                  21.2.0
array_record                          0.7.2
arviz                                 0.22.0
astropy                               7.1.0
astropy-iers-data                     0.2025.7.21.0.

In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [4, 2, 1]
])

print("First matrix is:")
print(a)
print("*********************************")

b = np.array([
    [2, 8, 0],
    [6, 3, 2],
    [4, 5, 7]
])

print("Second matrix is:")
print(b)
print("*********************************")

print("Addition of both matrices is")
print(a + b)
print("*********************************")

print("Subtraction of both matrices is")
print(a - b)
print("*********************************")

print("Multiplication of both matrices is")
print(np.dot(a, b))
print("*********************************")

print("Inversion of first matrix is")
z = np.linalg.inv(a)
print(z)


First matrix is:
[[1 2 3]
 [2 3 4]
 [4 2 1]]
*********************************
Second matrix is:
[[2 8 0]
 [6 3 2]
 [4 5 7]]
*********************************
Addition of both matrices is
[[ 3 10  3]
 [ 8  6  6]
 [ 8  7  8]]
*********************************
Subtraction of both matrices is
[[-1 -6  3]
 [-4  0  2]
 [ 0 -3 -6]]
*********************************
Multiplication of both matrices is
[[26 29 25]
 [38 45 34]
 [24 43 11]]
*********************************
Inversion of first matrix is
[[  5.  -4.   1.]
 [-14.  11.  -2.]
 [  8.  -6.   1.]]


In [ ]:
from google.colab import files

In [ ]:
files.upload()


Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"karanuderani","key":"5de9ac5ff58b525ff790101e1d526eb0"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json


In [ ]:
!pip install -q kaggle


In [ ]:
!kaggle datasets download -d rohanrao/nifty50-stock-market-data

Dataset URL: https://www.kaggle.com/datasets/rohanrao/nifty50-stock-market-data
License(s): CC0-1.0
  0% 0.00/18.4M [00:00<?, ?B/s]
100% 18.4M/18.4M [00:00<00:00, 1.09GB/s]


In [ ]:
!unzip nifty50-stock-market-data.zip

Archive:  nifty50-stock-market-data.zip
  inflating: ADANIPORTS.csv          
  inflating: ASIANPAINT.csv          
  inflating: AXISBANK.csv            
  inflating: BAJAJ-AUTO.csv          
  inflating: BAJAJFINSV.csv          
  inflating: BAJFINANCE.csv          
  inflating: BHARTIARTL.csv          
  inflating: BPCL.csv                
  inflating: BRITANNIA.csv           
  inflating: CIPLA.csv               
  inflating: COALINDIA.csv           
  inflating: DRREDDY.csv             
  inflating: EICHERMOT.csv           
  inflating: GAIL.csv                
  inflating: GRASIM.csv              
  inflating: HCLTECH.csv             
  inflating: HDFC.csv                
  inflating: HDFCBANK.csv            
  inflating: HEROMOTOCO.csv          
  inflating: HINDALCO.csv            
  inflating: HINDUNILVR.csv          
  inflating: ICICIBANK.csv           
  inflating: INDUSINDBK.csv          
  inflating: INFRATEL.csv            
  inflating: INFY.csv                
  inflatin

In [ ]:
import pandas as pd
import numpy as np

adani_ports = pd.read_csv("ADANIPORTS.csv")
asian_paint = pd.read_csv("ASIANPAINT.csv")
axis_bank = pd.read_csv("AXISBANK.csv")
tcs = pd.read_csv("TCS.csv")
tata_motors = pd.read_csv("TATAMOTORS.csv")
tata_steel = pd.read_csv("TATASTEEL.csv")
titan = pd.read_csv("TITAN.csv")
wipro = pd.read_csv("WIPRO.csv")
zeel = pd.read_csv("ZEEL.csv")
ntpc = pd.read_csv("NTPC.csv")
ongc = pd.read_csv("ONGC.csv")
kotak_bank = pd.read_csv("KOTAKBANK.csv")
jsw_steel = pd.read_csv("JSWSTEEL.csv")
maruti = pd.read_csv("MARUTI.csv")
reliance = pd.read_csv("RELIANCE.csv")
sunpharma = pd.read_csv("SUNPHARMA.csv")
bpcl = pd.read_csv("BPCL.csv")
britannia = pd.read_csv("BRITANNIA.csv")
bajajfinsv = pd.read_csv("BAJAJFINSV.csv")
bajfinance = pd.read_csv("BAJFINANCE.csv")
hdfc_bank = pd.read_csv("HDFCBANK.csv")
icici_bank = pd.read_csv("ICICIBANK.csv")
techm = pd.read_csv("TECHM.csv")

# Clean and prepare
all_dfs = [tata_motors, tata_steel, tcs, titan, wipro, zeel, ntpc, ongc, kotak_bank, jsw_steel,
           maruti, reliance, sunpharma, bpcl, britannia, bajajfinsv, bajfinance, hdfc_bank,
           icici_bank, techm, adani_ports, asian_paint]

for df in all_dfs:
    df.drop(['Trades', 'Deliverable Volume', '%Deliverble'], axis=1, inplace=True)
    df['Date'] = pd.to_datetime(df['Date'])

# Dictionary for lookup
stocks_dict = {
    'Adani Ports': adani_ports,
    'Asian Paint': asian_paint,
    'Axis Bank': axis_bank,
    'TCS': tcs,
    'Tata Motors': tata_motors,
    'Tata Steel': tata_steel,
    'Titan': titan,
    'Wipro': wipro,
    'ZEEL': zeel,
    'NTPC': ntpc,
    'ONGC': ongc,
    'Kotak Bank': kotak_bank,
    'JSW Steel': jsw_steel,
    'Maruti': maruti,
    'Reliance': reliance,
    'Sun Pharma': sunpharma,
    'BPCL': bpcl,
    'Britannia': britannia,
    'Bajaj Finserv': bajajfinsv,
    'Bajaj Finance': bajfinance,
    'HDFC Bank': hdfc_bank,
    'ICICI Bank': icici_bank,
    'Tech Mahindra': techm
}

# Functions with print output
def display_statistics(stock_name):
    stock = stocks_dict[stock_name]
    stats = stock['Close'].describe()
    print(f"Statistics for {stock_name}:\n{stats}\n")

def calculate_statistics(stock_name):
    stock = stocks_dict[stock_name]
    mean = np.mean(stock['Close'])
    variance = np.var(stock['Close'])
    std_dev = np.std(stock['Close'])
    print(f"{stock_name} Closing Price Statistics:")
    print(f"Mean: {mean:.2f}")
    print(f"Variance: {variance:.2f}")
    print(f"Standard Deviation: {std_dev:.2f}\n")

def correlation_between_stocks(stock1_name, stock2_name):
    stock1 = stocks_dict[stock1_name]['Close']
    stock2 = stocks_dict[stock2_name]['Close']
    correlation = stock1.corr(stock2)
    print(f"Correlation between {stock1_name} and {stock2_name}: {correlation:.2f}\n")

def show_recent_closing_prices(stock_name, num_days=5):
    stock = stocks_dict[stock_name]
    recent = stock[['Date', 'Close']].tail(num_days)
    print(f"Recent {num_days} closing prices for {stock_name}:\n{recent}\n")

def compare_recent_closes(stock1_name, stock2_name, num_days=5):
    s1 = stocks_dict[stock1_name][['Date', 'Close']].tail(num_days).reset_index(drop=True)
    s2 = stocks_dict[stock2_name][['Date', 'Close']].tail(num_days).reset_index(drop=True)
    comparison = pd.DataFrame({
        'Date': s1['Date'],
        stock1_name: s1['Close'],
        stock2_name: s2['Close']
    })
    print(f"Recent {num_days} day comparison:\n{comparison}\n")


In [ ]:
sample_stock = stocks_dict['TCS']

close_prices = sample_stock['Close'].to_numpy()

median_price = np.median(close_prices)
print("Median Close Price:", median_price)

max_price = np.max(close_prices)
min_price = np.min(close_prices)
print("Max Price:", max_price)
print("Min Price:", min_price)

cumsum_prices = np.cumsum(close_prices)
print("Cumulative Sum (first 5):", cumsum_prices[:5])

sorted_prices = np.sort(close_prices)
print("Sorted Close Prices (last 5):", sorted_prices[-5:])

noise = np.random.normal(0, 1, len(close_prices))
noisy_close = close_prices + noise
print("Noisy Prices Sample:", noisy_close[:5])



sample_stock['RollingAvg_7'] = sample_stock['Close'].rolling(window=7).mean()
print("7-day Rolling Avg (last 5):\n", sample_stock['RollingAvg_7'].tail())

sample_stock['Daily_Return'] = sample_stock['Close'].pct_change() * 100
print("Daily Return % (first 5):\n", sample_stock['Daily_Return'].head())

sample_stock['Close_Rank'] = sample_stock['Close'].rank()
print("Ranking by Close (last 5):\n", sample_stock[['Date', 'Close', 'Close_Rank']].tail())

sample_stock.set_index('Date', inplace=True)
print("Date set as index. DataFrame head:\n", sample_stock.head())

monthly_avg = sample_stock['Close'].resample('M').mean()
print("Monthly Avg Close:\n", monthly_avg.tail())


Median Close Price: 1636.35
Max Price: 3603.7
Min Price: 366.65
Cumulative Sum (first 5): [ 987.95 1966.95 2929.6  3916.35 4904.45]
Sorted Close Prices (last 5): [3532.1  3539.25 3556.75 3585.8  3603.7 ]
Noisy Prices Sample: [987.64502849 977.91947826 962.32937901 985.91182267 987.38811999]
7-day Rolling Avg (last 5):
 4134    3149.935714
4135    3137.514286
4136    3127.364286
4137    3120.714286
4138    3105.157143
Name: RollingAvg_7, dtype: float64
Daily Return % (first 5):
 0         NaN
1   -0.905916
2   -1.670072
3    2.503506
4    0.136813
Name: Daily_Return, dtype: float64
Ranking by Close (last 5):
            Date    Close  Close_Rank
4134 2021-04-26  3100.80      4043.0
4135 2021-04-27  3132.00      4062.0
4136 2021-04-28  3124.10      4060.0
4137 2021-04-29  3115.25      4054.0
4138 2021-04-30  3035.65      4019.0
Date set as index. DataFrame head:
            Symbol Series  Prev Close    Open    High     Low    Last   Close  \
Date                                          

/tmp/ipython-input-2863886565.py:37: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_avg = sample_stock['Close'].resample('M').mean()
