<a href="https://colab.research.google.com/github/Karanuderani07/ML_LEARNING/blob/main/Exp_9_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0],
              [1],
              [1],
              [0]])

np.random.seed(42)
W1 = np.random.randn(2, 2)
b1 = np.zeros((1, 2))
W2 = np.random.randn(2, 1)
b2 = np.zeros((1, 1))
lr = 0.5




In [ ]:
def forward(X):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)
    return z1, a1, z2, a2

def train_step(X, y):
    global W1, b1, W2, b2
    z1, a1, z2, a2 = forward(X)
    d_a2 = -(y - a2)
    d_z2 = d_a2 * sigmoid_derivative(z2)
    dW2 = np.dot(a1.T, d_z2)
    db2 = np.sum(d_z2, axis=0, keepdims=True)
    d_a1 = np.dot(d_z2, W2.T)
    d_z1 = d_a1 * sigmoid_derivative(z1)
    dW1 = np.dot(X.T, d_z1)
    db1 = np.sum(d_z1, axis=0, keepdims=True)
    W1 -= lr * dW1
    b1 -= lr * db1
    W2 -= lr * dW2
    b2 -= lr * db2
    loss = np.mean((y - a2) ** 2)
    return loss


In [ ]:

print("Initial W1:\n", W1)
print("Initial W2:\n", W2)

loss_before = np.mean((y - forward(X)[3]) ** 2)
print("Loss before:", loss_before)

loss_after = train_step(X, y)
print("Loss after:", loss_after)

print("Updated W1:\n", W1)
print("Updated W2:\n", W2)

Initial W1:
 [[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]]
Initial W2:
 [[-0.23415337]
 [-0.23413696]]
Loss before: 0.2558299419444368
Loss after: 0.2558299419444368
Updated W1:
 [[ 0.49502422 -0.14044231]
 [ 0.64606203  1.52244287]]
Updated W2:
 [[-0.20925282]
 [-0.21041497]]
