<a href="https://colab.research.google.com/github/Karanuderani07/ML_LEARNING/blob/main/hebbian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#"Neurons that fire together, wire together"

import numpy as np


X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])


Y = np.array([[0],
              [0],
              [0],
              [1]])

np.random.seed(42)
W = np.random.randn(2, 1)
lr = 0.1

print("Initial weights:\n", W)

for i in range(len(X)):
    x = X[i].reshape(2, 1)
    y = Y[i].reshape(1, 1)
    dW = lr * np.dot(x, y)
    W += dW
    print(f"\nAfter sample {i+1} (Input: {X[i]}, Output: {Y[i][0]}):")
    print("Weight update:\n", dW)
    print("Updated weights:\n", W)


Initial weights:
 [[ 0.49671415]
 [-0.1382643 ]]

After sample 1 (Input: [0 0], Output: 0):
Weight update:
 [[0.]
 [0.]]
Updated weights:
 [[ 0.49671415]
 [-0.1382643 ]]

After sample 2 (Input: [0 1], Output: 0):
Weight update:
 [[0.]
 [0.]]
Updated weights:
 [[ 0.49671415]
 [-0.1382643 ]]

After sample 3 (Input: [1 0], Output: 0):
Weight update:
 [[0.]
 [0.]]
Updated weights:
 [[ 0.49671415]
 [-0.1382643 ]]

After sample 4 (Input: [1 1], Output: 1):
Weight update:
 [[0.1]
 [0.1]]
Updated weights:
 [[ 0.59671415]
 [-0.0382643 ]]
